"""strategy team engine tables

Revision ID: 3a934d90f9b3
Revises: 0002_demo_overrides
Create Date: 2026-08-25 18:25:04.963719
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3a934d90f9b3'
down_revision: str | None = '0002_demo_overrides'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('allowed_tools_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('mission_types_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('input_schema_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('output_schema_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_minor', sa.BigInteger(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_agent_run_id'), 'usage_events', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_merchant_id'), 'usage_events', ['merchant_id'], unique=False)
    op.create_index('ix_usage_events_merchant_kind_created', 'usage_events', ['merchant_id', 'kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_mission_id'), 'usage_events', ['mission_id'], unique=False)
    op.create_table('baseline_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'version', name='uq_baseline_version')
    )
    op.create_index(op.f('ix_baseline_snapshots_merchant_id'), 'baseline_snapshots', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_baseline_snapshots_mission_id'), 'baseline_snapshots', ['mission_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('control_variant_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('treatment_variant_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('cohort_definition_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_merchant_id'), 'experiments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_experiments_mission_id'), 'experiments', ['mission_id'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('memory_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_memory_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_memory_id', name='uq_memory_provider_id')
    )
    op.create_index(op.f('ix_memory_refs_merchant_id'), 'memory_refs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_memory_refs_mission_id'), 'memory_refs', ['mission_id'], unique=False)
    op.create_table('merchant_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('geography', sa.String(length=255), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('pricing_model', sa.String(length=120), nullable=True),
    sa.Column('competitors_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('segments_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('products_summary_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('reputation_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_profiles_merchant_id'), 'merchant_profiles', ['merchant_id'], unique=True)
    op.create_table('merchant_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_sources_merchant_id'), 'merchant_sources', ['merchant_id'], unique=False)
    op.create_index('ix_merchant_sources_merchant_kind', 'merchant_sources', ['merchant_id', 'kind'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('mission_type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('budget_runs', sa.Integer(), nullable=False),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=False),
    sa.Column('agent_assignments_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('runs_used', sa.Integer(), nullable=False),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_merchant_id'), 'missions', ['merchant_id'], unique=False)
    op.create_index('ix_missions_merchant_status_created', 'missions', ['merchant_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_missions_merchant_type_created', 'missions', ['merchant_id', 'mission_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_missions_mission_type'), 'missions', ['mission_type'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('finding_ids_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('evidence_ids_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('suggested_next_mission_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_merchant_id'), 'recommendations', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recommendations_mission_id'), 'recommendations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=48), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('budget_tool_calls', sa.Integer(), nullable=False),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('llm_calls_used', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_minor', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_key'), 'agent_runs', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_runs_merchant_id'), 'agent_runs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_mission_id'), 'agent_runs', ['mission_id'], unique=False)
    op.create_index('ix_agent_runs_mission_status', 'agent_runs', ['mission_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('epistemic_state', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_agent_run_id'), 'evidence', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_merchant_id'), 'evidence', ['merchant_id'], unique=False)
    op.create_index('ix_evidence_mission_created', 'evidence', ['mission_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_evidence_mission_id'), 'evidence', ['mission_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('arm', sa.String(length=16), nullable=False),
    sa.Column('buyer_prompt', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('selection_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_runs_agent_run_id'), 'experiment_runs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_experiment_id'), 'experiment_runs', ['experiment_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('agent_key', sa.String(length=48), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ids_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_agent_run_id'), 'findings', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_findings_merchant_id'), 'findings', ['merchant_id'], unique=False)
    op.create_index('ix_findings_mission_created', 'findings', ['mission_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_findings_mission_id'), 'findings', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_mission_id'), table_name='findings')
    op.drop_index('ix_findings_mission_created', table_name='findings')
    op.drop_index(op.f('ix_findings_merchant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_agent_run_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_experiment_runs_experiment_id'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_agent_run_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_evidence_mission_id'), table_name='evidence')
    op.drop_index('ix_evidence_mission_created', table_name='evidence')
    op.drop_index(op.f('ix_evidence_merchant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_agent_run_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_parent', table_name='agent_runs')
    op.drop_index('ix_agent_runs_mission_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_mission_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_merchant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_key'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_mission_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_merchant_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_mission_type'), table_name='missions')
    op.drop_index('ix_missions_merchant_type_created', table_name='missions')
    op.drop_index('ix_missions_merchant_status_created', table_name='missions')
    op.drop_index(op.f('ix_missions_merchant_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index('ix_merchant_sources_merchant_kind', table_name='merchant_sources')
    op.drop_index(op.f('ix_merchant_sources_merchant_id'), table_name='merchant_sources')
    op.drop_table('merchant_sources')
    op.drop_index(op.f('ix_merchant_profiles_merchant_id'), table_name='merchant_profiles')
    op.drop_table('merchant_profiles')
    op.drop_index(op.f('ix_memory_refs_mission_id'), table_name='memory_refs')
    op.drop_index(op.f('ix_memory_refs_merchant_id'), table_name='memory_refs')
    op.drop_table('memory_refs')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_mission_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_merchant_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_baseline_snapshots_mission_id'), table_name='baseline_snapshots')
    op.drop_index(op.f('ix_baseline_snapshots_merchant_id'), table_name='baseline_snapshots')
    op.drop_table('baseline_snapshots')
    op.drop_index(op.f('ix_usage_events_mission_id'), table_name='usage_events')
    op.drop_index('ix_usage_events_merchant_kind_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_merchant_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_agent_run_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('strategy_agents')
    # ### end Alembic commands ###
