"""Deterministic policy reason codes (PRD §14).

Every block must map to one of these codes; the audit trail and UI rely on
them being stable identifiers.
"""

FINAL_AMOUNT_EXCEEDS_BUYER_AUTHORIZATION = "FINAL_AMOUNT_EXCEEDS_BUYER_AUTHORIZATION"
FINAL_AMOUNT_EXCEEDS_MERCHANT_LIMIT = "FINAL_AMOUNT_EXCEEDS_MERCHANT_LIMIT"
PRICE_CHANGED_SINCE_QUOTE = "PRICE_CHANGED_SINCE_QUOTE"
CART_TOTAL_MISMATCH = "CART_TOTAL_MISMATCH"
QUOTE_EXPIRED = "QUOTE_EXPIRED"
CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
CATEGORY_NOT_ALLOWED = "CATEGORY_NOT_ALLOWED"
BUYER_AUTHORIZATION_EXPIRED = "BUYER_AUTHORIZATION_EXPIRED"
INVENTORY_UNAVAILABLE = "INVENTORY_UNAVAILABLE"
VARIANT_UNAVAILABLE = "VARIANT_UNAVAILABLE"
VARIANT_NOT_FOUND = "VARIANT_NOT_FOUND"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
PRODUCT_ARCHIVED = "PRODUCT_ARCHIVED"
MERCHANT_INACTIVE = "MERCHANT_INACTIVE"
MERCHANT_CONSTRAINT_VIOLATION = "MERCHANT_CONSTRAINT_VIOLATION"
INVALID_TRANSACTION_STATE = "INVALID_TRANSACTION_STATE"

ALL_CODES: tuple[str, ...] = (
    FINAL_AMOUNT_EXCEEDS_BUYER_AUTHORIZATION,
    FINAL_AMOUNT_EXCEEDS_MERCHANT_LIMIT,
    PRICE_CHANGED_SINCE_QUOTE,
    CART_TOTAL_MISMATCH,
    QUOTE_EXPIRED,
    CURRENCY_MISMATCH,
    CATEGORY_NOT_ALLOWED,
    BUYER_AUTHORIZATION_EXPIRED,
    INVENTORY_UNAVAILABLE,
    VARIANT_UNAVAILABLE,
    VARIANT_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    PRODUCT_ARCHIVED,
    MERCHANT_INACTIVE,
    MERCHANT_CONSTRAINT_VIOLATION,
    INVALID_TRANSACTION_STATE,
)
